Unquoting + New Parser + New internal AST
densh/scala-xml-quote pull request #14
Opened 2017-03-29 21:09 UTC by allanrenucci

2017-03-29 21:10 UTC, allanrenucci commented
@densh Can you have a look?

2017-03-29 21:12 UTC, allanrenucci commented on src/main/scala/scala/xml/quote/internal/Liftables.scala
> +    //implicit val isTopScopeNext: Boolean = isTopScope && nss.isEmpty
I want to shadow the previous implicit but it fails to compile

2017-03-31 15:33 UTC, allanrenucci commented on src/main/scala/scala/xml/quote/internal/Liftables.scala
> +        api.typecheck(scopeId)
@densh It fails to typecheck this with the error: ` not found: value $scope$`

2017-03-31 15:41 UTC, allanrenucci commented on src/main/scala/scala/xml/quote/internal/Liftables.scala
> +        api.typecheck(scopeId)
Before fixing the tree:
```scala
{
  val $tmpscope = _root_.scala.xml.NamespaceBinding("pre", "scope0", _root_.scala.xml.TopScope);
  {
    val $scope$ = $tmpscope;
    _root_.scala.xml.Elem(((null): String), "a", _root_.scala.xml.Null, $scope$, false, (({
      val $buf = new _root_.scala.xml.NodeBuffer();
      $buf.&+(((scala.xml.Elem.apply(((null): scala.Predef.String), "b", scala.xml.Null, scala.xml.TopScope, true, (({
        val $buf = new scala.xml.NodeBuffer();
        $buf
      }): _*))): scala.xml.Node));
      $buf
    }): _*))
  }
}
```
after fixing the tree
```scala
[error] /Users/renucci/Documents/Projects/scala-xml-quote/src/test/scala/ConstructionSuite.scala:106: not found: value $scope$
[error]     val xml1 =
[error]         ^
{
  val $tmpscope = _root_.scala.xml.NamespaceBinding("pre", "scope0", $scope$);
  {
    val $scope$ = $tmpscope;
    _root_.scala.xml.Elem(((null): String), "a", _root_.scala.xml.Null, $scope$, false, (({
      val $buf = new _root_.scala.xml.NodeBuffer();
      $buf.&+(((scala.xml.Elem.apply(((null): scala.Predef.String), "b", scala.xml.Null, $scope$, true, (({
        val $buf = new scala.xml.NodeBuffer();
        $buf
      }): _*))): scala.xml.Node));
      $buf
    }): _*))
  }
}
```
The transformed tree looks correct to me

2017-03-31 17:44 UTC, allanrenucci commented on src/main/scala/scala/xml/quote/internal/Liftables.scala
> +        api.typecheck(q"$$scope$$")
@densh This doesn't work. It fails with `not found: value $scope$`

Here is the generated code for `xml"""<a xmlns:pre="scope0">${ xml"<b/>" }</a>"""`:
Before fixing scopes:
```scala
{
  val $tmpscope = _root_.scala.xml.NamespaceBinding("pre", "scope0", _root_.scala.xml.TopScope);
  {
    val $scope$ = $tmpscope;
    _root_.scala.xml.Elem(((null): String), "a", _root_.scala.xml.Null, $scope$, false, (({
      val $buf = new _root_.scala.xml.NodeBuffer();
      $buf.&+(((scala.xml.Elem.apply(((null): scala.Predef.String), "b", scala.xml.Null, scala.xml.TopScope, true, (({
        val $buf = new scala.xml.NodeBuffer();
        $buf
      }): _*))): scala.xml.Node));
      $buf
    }): _*))
  }
}
```
After fixing the scopes:
```scala
{
  val $tmpscope = _root_.scala.xml.NamespaceBinding("pre", "scope0", _root_.scala.xml.TopScope);
  {
    val $scope$ = $tmpscope;
    _root_.scala.xml.Elem(((null): String), "a", _root_.scala.xml.Null, $scope$, false, (({
      val $buf = new _root_.scala.xml.NodeBuffer();
      $buf.&+(((scala.xml.Elem.apply(((null): scala.Predef.String), "b", scala.xml.Null, $scope$, true, (({
        val $buf = new scala.xml.NodeBuffer();
        $buf
      }): _*))): scala.xml.Node));
      $buf
    }): _*))
  }
}
```
This compiles if I paste it in a repl. So it fails to typecheck during macro expansion. I don't know though...

2017-04-04 09:06 UTC, densh requested changes
First pass.

2017-04-04 09:06 UTC, densh commented on src/main/scala/scala/xml/quote/internal/Liftables.scala
> +    })
This should go to `QuoteImpl`.

2017-04-04 09:06 UTC, densh commented on src/main/scala/scala/xml/quote/internal/XmlParser.scala
> +// FIXME tag must be balanced
I guess we can delay for next PR that would deal with error handling and positions.

2017-04-04 09:06 UTC, densh commented on src/test/scala/ConstructionSuite.scala
> +    def ====(that: xml.NodeBuffer): Boolean = {
How about we use `≈` for this. It's a bit more readable and super easy to type via Opt+X on Mac.

2017-04-04 09:06 UTC, densh commented on src/main/scala/scala/xml/quote/internal/QuoteImpl.scala
> +    assert(nodes.size > 1)
Lets just wrap into a single-element sequence instead of failing here.

2017-04-04 09:06 UTC, densh commented on src/test/scala/ConstructionSuite.scala
> +  }
Lets have more tests on namespaces, given that it's a hard-ish part of the problem.

2017-04-04 09:06 UTC, densh commented on src/test/scala/ConstructionSuite.scala
> +      </a>
Does this always preserve the whitespace consistently?

2017-04-05 17:11 UTC, allanrenucci commented
@densh While writing a bunch of tests, I realised the semantic of scalac has changed between 2.11 and 2.12.
```scala
scala2.11> reify(<foo>bar&#50;</foo>)
res2: reflect.runtime.universe.Expr[scala.xml.Elem] =
Expr[scala.xml.Elem]({
  {
    new Elem(null, "foo", Null, TopScope, false, ({
      val $buf = new NodeBuffer();
      $buf.$amp$plus(new Text("bar2"));
      $buf
    }: _*))
  }
})
```
```scala
scala2.12>  reify(<foo>bar&#50;</foo>)
res68: reflect.runtime.universe.Expr[scala.xml.Elem] =
Expr[scala.xml.Elem]({
  {
    new Elem(null, "foo", Null, TopScope, false, ({
      val $buf = new NodeBuffer();
      $buf.$amp$plus(new Text("bar"));
      $buf.$amp$plus(new Text("2"));
      $buf
    }: _*))
  }
})
```
I am not sure what to do... (I currently support scala2.12 semantic)

2017-04-11 11:58 UTC, densh commented
Woohoo, well done @allanrenucci !

2017-04-11 11:58 UTC, densh approved these changes

2017-04-11 11:59 UTC, merged